---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("PGHOST", 'db') %>
  port: <%= ENV.fetch("PGPORT", 5432) %>
  username: <%= ENV.fetch("PGUSER", 'postgres') %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  # connect_timeout: 2
  # checkout_timeout: 5
  # variables:
  #   statement_timeout: 5000

development:
  <<: *default
  database: backend_development

test:
  <<: *default
  database: backend_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: backend_production
