---
:verbose: false
:concurrency: 5
:timeout: 25

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - [critical, 3]
  - [default, 2]
  # - <%= `hostname`.strip %>
  - low
# # you can override concurrency based on environment
# production:
#   :concurrency: 25
# staging:
#   :concurrency: 15
