source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

gem "bootsnap", ">= 1.4.4", require: false
gem "hiredis"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "rack-cors"
gem "rails", "~> 7.0.0.alpha2"
gem "redis", "~> 4.0", require: ["redis", "redis/connection/hiredis"]

gem "activerecord-postgres_enum",
  github: "noelrappin/activerecord-postgres_enum",
  branch: "master"
gem "after_commit_everywhere"
gem "anyway_config"
gem "awesome_rails_console",
  github: "xunker/awesome_rails_console",
  branch: "pry-0.13.0-compatibility"
gem "down"
gem "dry-transaction"
gem "dry-validation"
gem "fast_blank", platform: :mri
gem "finnhub_ruby"
gem "graphql"
gem "graphql-batch"
gem "image_processing"
gem "mobility"
gem "money"
gem "nilify_blanks"
gem "sidekiq"
gem "strong_migrations"
gem "translate_enum"

group :development, :test do
  gem "debug", ">= 1.0.0", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "factory_trace"
  gem "graphiql-rails"
  # gem "isolator"
  gem "parallel_tests"
  gem "routes_lazy_routes"
  gem "rspec-rails"
end

group :development do
  gem "brakeman", require: false
  # gem "bullet"
  gem "bundler-audit", require: false
  gem "ordinare", require: false
  gem "ruby_audit", require: false
  gem "standard"
end

group :test do
  gem "faker"
  gem "rspec-sidekiq"
  gem "rspec_junit_formatter"
  gem "simplecov"
  gem "simplecov-console"
  gem "test-prof"
  gem "vcr"
  gem "webmock"
  gem "zonebie"
end
